spring:
   application:
      name: account-service

server:
   port: 8305

eureka:
   client:
      registerWithEureka: true
      fetchRegistery: true
      serviceUrl:
         defaultZone: http://localhost:8302/eureka/
   instance:
      hostname: localhost